name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'DavidBerdik/Universal-Audio-Capture-Enabler-for-Android'
        ref: 'audio-capture-enabler-fork'
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Accept SDK licenses
      run: |
        cd $ANDROID_SDK_ROOT/tools/bin
        yes | ./sdkmanager --licenses
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: SSH connection to Actions to debug
      uses: P3TERX/ssh2actions@v1.0.0
      if: failure()
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.sha }}
        path: app/build/outputs/apk
